# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_like_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='main.Cat'),
        ),
    ]
